name: ace_plus_code_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  retrofit: ^3.3.1
  pretty_dio_logger: ^1.1.1
  json_annotation: ^4.7.0
  flutter_easyloading: ^3.0.5
  dio: ^4.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter: 
  uses-material-design: true

